repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Increase limit to 1MB to accomodate the distilled MITRE ATT&CK data JSON file
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--indent=4"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
