# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: isort
        name: isort
        description: Automatically sort all import statements
        types_or: [cython, pyi, python]
        entry: poetry run isort
        args: ["-l", "88", "-m", "3", "--profile", "black", "--combine-as"]
        language: system
        types: [file, python]
    -   id: autoflake
        name: autoflake
        description: Automatically remove all unused imports and redundant pass statements
        entry: poetry run autoflake
        args: ["--remove-all-unused-imports"]
        language: system
        types: [file, python]
    -   id: add-trailing-comma
        name: add-trailing-comma
        entry: poetry run add-trailing-comma
        language: system
        types: [file, python]
    -   id: ruff
        name: ruff
        description: Automatically format source code to the PEP8 specification with ruff
        entry: poetry run ruff format
        language: system
        types: [file, python]
