site_name: Consortium
site_author: not-sekiun
site_description:
  Consortium is a programming language agnostic, and networking
  protocol agnostic command and control (C2) framework that is designed to be
  collaborative, highly extensible, and modular

repo_url: https://github.com/not-sekiun/PyIris
repo_name: not-sekiun/Consortium
edit_uri: docs/

copyright: Copyright &copy; 2016 - 2024 not-sekiun

theme:
  name: material
  font:
    code: JetBrains mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
#  - Exceptions: test.md
#  - Home: index.md
#  - About:
#    - about/features.md
#    - about/motivation.md
#    - about/history.md
#  - Getting Started:
#    - getting-started/installation.md
#    - getting-started/updating.md
#    - getting-started/quick-start.md
#  - Manual:
#    - manual/introduction.md
#  - Server API:
#    - Events Websockets API:
#      - events-websockets-api/introduction.md
#      - events-websockets-api/authentication.md
#      - events-websockets-api/sending-action-commands.md
#    - REST API:
#      - rest-api/introduction.md
#  - Framework Reference:
#    - Framework:
#      - framework-reference/framework/listeners-reference.md
#      - framework-reference/framework/agent-generators-reference.md
#      - framework-reference/framework/plugins-reference.md
#      - framework-reference/framework/event-hooks-reference.md
#      - framework-reference/framework/options-reference.md
#    - Exceptions:
#      - framework-reference/exceptions/signalling-exceptions.md
#      - framework-reference/exceptions/plugins-framework-exceptions.md
#      - framework-reference/exceptions/options-framework-exceptions.md
#      - framework-reference/exceptions/listeners-framework-exceptions.md
  - Services Reference:
#      - Services:
#        - services-reference/services/plugins-service-reference.md
      - Exceptions:
        - services-reference/exceptions/listener-templates-service-exceptions.md
        - services-reference/exceptions/agent-templates-service-exceptions.md
        - services-reference/exceptions/plugins-service-exceptions.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          parameter_headings: true
          filters:
          - '!^_'
          docstring_options:
            show_docstring_description: true
            show_docstring_attributes: false
            show_docstring_methods: false

watch:
- ../consortium

extra_javascript:
  - javascripts/asciinema-player.min.js
extra_css:
  - stylesheets/asciinema-player.css
