site_name: Consortium
site_author: not-sekiun
site_description:
  Consortium is a programming language agnostic, and networking
  protocol agnostic command and control (C2) framework that is designed to be
  collaborative, highly extensible, and modular
site_url: https://not-sekiun.github.io/Consortium/

repo_url: https://github.com/not-sekiun/PyIris
repo_name: not-sekiun/Consortium
edit_uri: docs/

copyright: Copyright &copy; 2016 - 2024 not-sekiun

theme:
  name: material
  font:
    code: JetBrains mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png

nav:
  - Home: index.md
#  - About:
#    - about/features.md
#    - about/motivation.md
#    - about/history.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/updating.md
    - getting-started/quick-start.md
  - Server API:
    - REST API:
      - server-api/rest-api/introduction.md
    - Events Websockets API:
      - server-api/events-websockets-api/introduction.md
      - server-api/events-websockets-api/authentication.md
      - server-api/events-websockets-api/sending-action-commands.md
      - server-api/events-websockets-api/server-messages.md
  - Framework:
    - Listeners:
      - framework/listeners/listeners-overview.md
      - Building a Listener Profile:
        - framework/listeners/building-a-listener-profile/listener-type.md
        - framework/listeners/building-a-listener-profile/listener-template.md
        - framework/listeners/building-a-listener-profile/listener.md
        - framework/listeners/building-a-listener-profile/complete-listener-profile.md
    - Agents:
      - framework/agents/agents-overview.md
      - Building an Agent Profile:
        - framework/agents/building-an-agent-profile/agent-capabilities.md
        - framework/agents/building-an-agent-profile/agent-type.md
        - framework/agents/building-an-agent-profile/agent-template.md
        - framework/agents/building-an-agent-profile/agent-generator.md
        - framework/agents/building-an-agent-profile/complete-agent-profile.md
      - Building an Agent:
      - framework/agents/agent-protocol.md
    - Plugins:
      - framework/plugins/plugins-overview.md
      - Building a Plugin:
        - framework/plugins/building-a-plugin/project-setup.md
        - framework/plugins/building-a-plugin/plugin-metadata.md
        - framework/plugins/building-a-plugin/plugin-startup.md
        - framework/plugins/building-a-plugin/plugin-running-loop.md
        - framework/plugins/building-a-plugin/plugin-shutdown.md
        - framework/plugins/building-a-plugin/plugin-error-handling.md
        - framework/plugins/building-a-plugin/plugin-conventions.md
        - framework/plugins/building-a-plugin/complete-plugin-example.md
    - Event Hooks:
        - framework/event-hooks/event-hooks-overview.md
        - Building an Event Hook:
          - framework/event-hooks/building-an-event-hook/project-setup.md
          - framework/event-hooks/building-an-event-hook/event-hook-metadata.md
          - framework/event-hooks/building-an-event-hook/event-hook-setup.md
          - framework/event-hooks/building-an-event-hook/event-hook-triggering.md
          - framework/event-hooks/building-an-event-hook/event-hook-teardown.md
          - framework/event-hooks/building-an-event-hook/event-hook-conventions.md
          - framework/event-hooks/building-an-event-hook/complete-event-hook-example.md
        - framework/event-hooks/event-types.md
  - Reference:
      - Services:
        - reference/services/agents-service-reference.md
        - reference/services/agent-file-manager-service-reference.md
        - reference/services/agent-generators-service-reference.md
        - reference/services/agent-profile-loader-service-reference.md
        - reference/services/agent-profiles-service-reference.md
        - reference/services/agent-templates-service-reference.md
        - reference/services/artifacts-service-reference.md
        - reference/services/assets-service-reference.md
        - reference/services/authorization-service-reference.md
        - reference/services/c2-types-service-reference.md
        - reference/services/connected-agents-service-reference.md
        - reference/services/consortium-paths-service-reference.md
        - reference/services/event-hook-loader-service.md
        - reference/services/event-hooks-service-reference.md
        - reference/services/events-service-reference.md
        - reference/services/listener-profile-loader-service-reference.md
        - reference/services/listener-profiles-service-reference.md
        - reference/services/listener-templates-service-reference.md
        - reference/services/listeners-service-reference.md
        - reference/services/logging-service-reference.md
        - reference/services/payloads-service-reference.md
        - reference/services/plugins-service-reference.md
        - reference/services/plugin_loader_service.md
        - reference/services/release-service-reference.md
        - reference/services/repository-service-reference.md
        - reference/services/user-accounts-service-reference.md
        - reference/services/users-service-reference.md
      - Consortium Exceptions:
        - reference/exceptions/base-consortium-error.md
        - reference/exceptions/agents-errors.md
        - reference/exceptions/agent-capabilities-errors.md
        - reference/exceptions/agent-generators-errors.md
        - reference/exceptions/agent-profiles-errors.md
        - reference/exceptions/agent-templates-errors.md
        - reference/exceptions/c2-types-errors.md
        - reference/exceptions/components-errors.md
        - reference/exceptions/events-errors.md
        - reference/exceptions/event-hooks-errors.md
        - reference/exceptions/listeners-errors.md
        - reference/exceptions/listener-profiles-errors.md
        - reference/exceptions/listener-templates-errors.md
        - reference/exceptions/options-errors.md
        - reference/exceptions/payloads-errors.md
        - reference/exceptions/plugins-errors.md
        - reference/exceptions/repository-errors.md
        - reference/exceptions/users-errors.md
        - reference/exceptions/user-accounts-errors.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          parameter_headings: true
          show_source: false
          filters:
          - '!^_'
          docstring_options:
            show_docstring_description: true
            show_docstring_attributes: false
            show_docstring_methods: false

watch:
- consortium
- docs
- mkdocs.yaml

extra_javascript:
  - javascripts/asciinema-player.min.js

extra_css:
  - stylesheets/asciinema-player.css
