from consortium.client.repl_framework.base_command import ReturnStatusType


class InterpreterType:
    HOME_INTERPRETER = "HOME_INTERPRETER"
    LISTENERS_INTERPRETER = "LISTENERS_INTERPRETER"
    AGENTS_INTERPRETER = "AGENTS_INTERPRETER"
    GENERATORS_INTERPRETER = "GENERATORS_INTERPRETER"
    USE_LISTENER_TEMPLATE_INTERPRETER = "USE_LISTENER_TEMPLATE_INTERPRETER"
    USE_AGENT_TEMPLATE_INTERPRETER = "USE_AGENT_TEMPLATE_INTERPRETER"
    INTERACT_AGENT_INTERPRETER = "INTERACT_AGENT_INTERPRETER"


class ClientReturnStatusType(ReturnStatusType):
    SWITCH_INTERPRETER = "SWITCH_INTERPRETER"
    EXIT_CLIENT_SESSION = "EXIT_CLIENT_SESSION"
    SWITCH_CLIENT_SESSION = "SWITCH_CLIENT_SESSION"
