from enum import StrEnum, unique


@unique
class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    SPECTATOR = "SPECTATOR"


@unique
class UserPermissions(StrEnum):
    # Permissions for the /api/user_accounts endpoint
    CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT"
    READ_OWN_USER_ACCOUNT = "READ_OWN_USER_ACCOUNT"
    READ_USER_ACCOUNT_BY_USER_ACCOUNT_ID = "READ_USER_ACCOUNT_BY_USER_ACCOUNT_ID"
    READ_ALL_USER_ACCOUNTS = "READ_ALL_USER_ACCOUNTS"
    UPDATE_OWN_USER_ACCOUNT_PASSWORD = "UPDATE_OWN_USER_ACCOUNT_PASSWORD"
    UPDATE_USER_ACCOUNT_PASSWORD_BY_USER_ACCOUNT_ID = (
        "UPDATE_USER_ACCOUNT_PASSWORD_BY_USER_ACCOUNT_ID"
    )
    UPDATE_USER_ACCOUNT_ROLE_BY_USER_ACCOUNT_ID = (
        "UPDATE_USER_ACCOUNT_ROLE_BY_USER_ACCOUNT_ID"
    )
    DELETE_OWN_USER_ACCOUNT = "DELETE_OWN_USER_ACCOUNT"
    DELETE_USER_ACCOUNT_BY_USER_ACCOUNT_ID = "DELETE_USER_ACCOUNT_BY_USER_ACCOUNT_ID"

    # Permissions for the /api/users endpoint
    READ_OWN_USER_INFO = "READ_OWN_USER_INFO"
    READ_ALL_USERS_INFO = "READ_ALL_USERS_INFO"
    READ_USER_INFO_BY_USER_ID = "READ_USER_INFO_BY_USER_ID"

    # Permissions for the /api/server endpoint
    READ_SERVER_RELEASE = "READ_SERVER_RELEASE"
    READ_SERVER_CONFIG = "READ_SERVER_CONFIG"

    # Permissions for the /api/listener_templates endpoint
    READ_ALL_LISTENER_TEMPLATES_INFO = "READ_ALL_LISTENER_TEMPLATES_INFO"
    READ_LISTENER_TEMPLATE_INFO_BY_LISTENER_TEMPLATE_ID = (
        "READ_LISTENER_TEMPLATE_INFO_BY_LISTENER_TEMPLATE_ID"
    )
    CREATE_LISTENER = "CREATE_LISTENER"

    # PERMISSIONS FOR THE /api/listeners endpoint
    READ_ALL_LISTENERS_INFO = "READ_ALL_LISTENERS_INFO"
    READ_LISTENER_INFO_BY_LISTENER_ID = "READ_LISTENER_INFO_BY_LISTENER_ID"
    START_LISTENER_BY_LISTENER_ID = "START_LISTENER_BY_LISTENER_ID"
    STOP_LISTENER_BY_LISTENER_ID = "STOP_LISTENER_BY_LISTENER_ID"
