from enum import StrEnum, unique


@unique
class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    SPECTATOR = "SPECTATOR"


@unique
class UserPermissions(StrEnum):
    # Permissions for the /api/user-accounts endpoint
    CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT"
    READ_USER_ACCOUNT_BY_USER_ACCOUNT_ID = "READ_USER_ACCOUNT_BY_USER_ACCOUNT_ID"
    READ_ALL_USER_ACCOUNTS = "READ_ALL_USER_ACCOUNTS"
    UPDATE_OWN_USER_ACCOUNT_USERNAME = "UPDATE_OWN_USER_ACCOUNT_USERNAME"
    UPDATE_OWN_USER_ACCOUNT_PASSWORD = "UPDATE_OWN_USER_ACCOUNT_PASSWORD"
    UPDATE_USER_ACCOUNT_USERNAME_BY_USER_ACCOUNT_ID = (
        "UPDATE_USER_ACCOUNT_USERNAME_BY_USER_ACCOUNT_ID"
    )
    UPDATE_USER_ACCOUNT_PASSWORD_BY_USER_ACCOUNT_ID = (
        "UPDATE_USER_ACCOUNT_PASSWORD_BY_USER_ACCOUNT_ID"
    )
    UPDATE_USER_ACCOUNT_ROLE_BY_USER_ACCOUNT_ID = (
        "UPDATE_USER_ACCOUNT_ROLE_BY_USER_ACCOUNT_ID"
    )
    DELETE_USER_ACCOUNT_BY_USER_ACCOUNT_ID = "DELETE_USER_ACCOUNT_BY_USER_ACCOUNT_ID"

    # Permissions for the /api/users endpoint
    READ_OWN_USER = "READ_OWN_USER"
    READ_ALL_USERS = "READ_ALL_USERS"
    READ_USER_BY_USER_ID = "READ_USER_BY_USER_ID"

    # Permissions for the /api/server endpoint
    READ_SERVER_RELEASE = "READ_SERVER_RELEASE"
    READ_SERVER_CONFIG = "READ_SERVER_CONFIG"

    # Permissions for the /api/listener-templates endpoint
    CREATE_LISTENER = "CREATE_LISTENER"
    READ_ALL_LISTENER_TEMPLATES = "READ_ALL_LISTENER_TEMPLATES"
    READ_LISTENER_TEMPLATE_BY_LISTENER_TEMPLATE_ID = (
        "READ_LISTENER_TEMPLATE_BY_LISTENER_TEMPLATE_ID"
    )

    # Permissions for the /api/listeners endpoint
    READ_ALL_LISTENERS = "READ_ALL_LISTENERS"
    READ_LISTENER_BY_LISTENER_ID = "READ_LISTENER_BY_LISTENER_ID"
    START_LISTENER_BY_LISTENER_ID = "START_LISTENER_BY_LISTENER_ID"
    STOP_LISTENER_BY_LISTENER_ID = "STOP_LISTENER_BY_LISTENER_ID"
    CANCEL_LISTENER_BY_LISTENER_ID = "CANCEL_LISTENER_BY_LISTENER_ID"
    UPDATE_LISTENER_BY_LISTENER_ID = "UPDATE_LISTENER_BY_LISTENER_ID"
    DELETE_LISTENER_BY_LISTENER_ID = "DELETE_LISTENER_BY_LISTENER_ID"

    # Permissions for the /api/agent-templates endpoint
    CREATE_AGENT_GENERATOR = "CREATE_AGENT_GENERATOR"
    READ_ALL_AGENT_TEMPLATES = "READ_ALL_AGENT_TEMPLATES"
    READ_AGENT_TEMPLATE_BY_AGENT_TEMPLATE_ID = (
        "READ_AGENT_TEMPLATE_BY_AGENT_TEMPLATE_ID"
    )

    # Permissions for the /api/agent-generators endpoint
    READ_ALL_AGENT_GENERATORS = "READ_ALL_AGENT_GENERATORS"
    READ_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "READ_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )
    START_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "START_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )
    STOP_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "STOP_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )
    CANCEL_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "CANCEL_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )
    UPDATE_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "UPDATE_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )
    DELETE_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID = (
        "DELETE_AGENT_GENERATOR_BY_AGENT_GENERATOR_ID"
    )

    # Permissions for the /api/agents endpoint
    READ_ALL_AGENTS = "READ_ALL_AGENTS"
    READ_AGENT_BY_AGENT_ID = "READ_AGENT_BY_AGENT_ID"
    READ_ALL_AGENT_TASKS_BY_AGENT_ID = "READ_ALL_AGENT_TASKS_BY_AGENT_ID"
    READ_AGENT_TASK_BY_AGENT_ID_AND_TASK_ID = "READ_AGENT_TASK_BY_AGENT_ID_AND_TASK_ID"
    READ_ALL_AGENT_RESULTS_BY_AGENT_ID = "READ_ALL_AGENT_RESULTS_BY_AGENT_ID"
    READ_AGENT_RESULT_BY_AGENT_ID_AND_TASK_ID_OR_RESULT_ID = (
        "READ_AGENT_RESULT_BY_AGENT_ID_AND_TASK_ID_OR_RESULT_ID"
    )
    TASK_AGENT_BY_AGENT_ID = "TASK_AGENT_BY_AGENT_ID"
    DELETE_AGENT_TASK_BY_AGENT_TASK_ID = "DELETE_AGENT_TASK_BY_AGENT_TASK_ID"
