from typing import Generic, TypeVar

from pydantic import BaseModel, JsonValue, create_model

from consortium.framework._core.framework_exceptions.base_framework_exception import (
    BaseFrameworkError,
)
from consortium.server.exceptions.object_exceptions.base_object_exception import (
    BaseObjectError,
)
from consortium.server.exceptions.service_exceptions.base_service_exception import (
    BaseServiceError,
)

T = TypeVar("T")


class BaseAPIError(Exception):
    status_code: int
    code: str | None = None

    # This ensures that there is ever only a single instance of the pydantic model
    # within the entire framework. This is important because duplicate pydantic models
    # with the same name will cause the OpenAPI schema to attempt name mangling leading
    # to ugly schema names. Note that _pydantic_models is a list that is shared amongst
    # all instances of this class and its subclasses.
    _pydantic_models = []

    # We do not combine the non-null and null detail error models into a single model
    # because an error response will only ever return ONE of the two, not possibly
    # either.
    class NonNullDetailErrorModel(BaseModel, Generic[T]):
        code: str
        message: str
        detail: T

    # Using detail: Any | None = None or Any = None as the pydantic field does not work,
    # the swagger UI refuses to properly render the response model hence the model
    # splitting
    class NullDetailErrorModel(BaseModel):
        code: str
        message: str
        detail: type[None]

    def __init__(
        self,
        message: str = "",
        detail: dict[str, JsonValue] | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.message = message
        self.detail = detail
        self.headers = headers

        super().__init__(message)

    def to_json(self) -> dict[str, JsonValue]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "detail": self.detail,
            },
        }

    def to_pydantic_model(self) -> type[BaseModel]:
        # Prevent duplication of pydantic models to keep the OpenAPI schema clean.
        for existing_pydantic_model in self._pydantic_models:
            # Check if the existing pydantic model is functionally the same as the
            # current one
            if (
                existing_pydantic_model.model_config["json_schema_extra"]["examples"][0]
                == self.to_json()
            ):
                return existing_pydantic_model

        pydantic_model = create_model(
            f"{self.__class__.__name__}Model",
            error=(
                (
                    self.__class__.NonNullDetailErrorModel[type(self.detail)]
                    if self.detail is not None
                    else self.__class__.NullDetailErrorModel
                ),
                ...,
            ),
        )
        pydantic_model.model_config = {
            "json_schema_extra": {
                "examples": [
                    {
                        "error": {
                            "code": self.code,
                            "message": self.message,
                            # If self.detail is None, this will not be included in
                            # the /openapi.json file that is generated by FastAPI
                            # (https://github.com/tiangolo/fastapi/issues/1082). A
                            # workaround is to manually add in the null detail which
                            # is done in server.py
                            "detail": self.detail,
                        },
                    },
                ],
            },
        }
        self._pydantic_models.append(pydantic_model)
        return pydantic_model

    @classmethod
    def from_consortium_exception(
        cls,
        consortium_exception: BaseServiceError | BaseFrameworkError | BaseObjectError,
    ) -> BaseAPIError:
        api_exception = cls(
            message=consortium_exception.message,
            detail=consortium_exception.detail,
        )
        own_code = cls.__dict__.get("code")
        api_exception.code = (
            own_code if own_code is not None else consortium_exception.code
        )
        return api_exception
