from typing import ClassVar

from pydantic import BaseModel, ConfigDict, JsonValue, create_model

from consortium.framework._core.framework_exceptions.base_framework_exception import (
    BaseFrameworkError,
)
from consortium.server.exceptions.object_exceptions.base_object_exception import (
    BaseObjectError,
)
from consortium.server.exceptions.service_exceptions.base_service_exception import (
    BaseServiceError,
)
from consortium.server.models.error_models import ErrorModel


class BaseAPIError(Exception):
    status_code: ClassVar[int]
    code: ClassVar[str | None] = None

    # This ensures that there is ever only a single instance of the pydantic model
    # within the entire framework. This is important because duplicate pydantic models
    # with the same name will cause the OpenAPI schema to attempt name mangling leading
    # to ugly schema names. Note that _pydantic_models is a dict that is shared amongst
    # all instances of this class and its subclasses.
    _pydantic_models: ClassVar[dict[type, type[BaseModel]]] = {}

    def __init__(
        self,
        message: str = "",
        detail: dict[str, JsonValue] | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.message = message
        self.detail = detail
        self.headers = headers

        super().__init__(message)

    def to_json(self) -> dict[str, JsonValue]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "detail": self.detail,
            },
        }

    def to_pydantic_model(self) -> type[BaseModel]:
        cache_key = self.__class__
        # Prevent duplication of pydantic models to keep the OpenAPI schema clean. We
        # check if the exception class already has a created pydantic error model and
        # reuse it if it exists. This makes it so that the same exception class with
        # different messages reuses the model.
        if cache_key in self._pydantic_models:
            return self._pydantic_models[cache_key]

        # ErrorModel carries a nullable detail (anyOf: [object, null]). The null branch
        # types the null detail rather than leaving it untyped ("any"), while the object
        # branch gives OpenAPI client generators (openapi-generator's Python codegen,
        # 7.17+) a concrete type to map to. A null-only `{"type": "null"}` property has no
        # such branch and crashes those generators. Which shape a specific endpoint
        # returns (object vs null) is documented by the per-response example below.
        pydantic_model = create_model(
            f"{self.__class__.__name__}Model",
            error=(ErrorModel, ...),
        )
        pydantic_model.model_config = ConfigDict(
            json_schema_extra={
                "examples": [
                    {
                        "error": {
                            "code": self.code,
                            "message": self.message,
                            # If self.detail is None, this will not be included in
                            # the /openapi.json file that is generated by FastAPI
                            # (https://github.com/tiangolo/fastapi/issues/1082). A
                            # workaround is to manually add in the null detail which
                            # is done in server.py
                            "detail": self.detail,
                        },
                    },
                ],
            }
        )
        self._pydantic_models[cache_key] = pydantic_model
        return pydantic_model

    @classmethod
    def from_consortium_exception(
        cls,
        consortium_exception: BaseServiceError | BaseFrameworkError | BaseObjectError,
    ) -> BaseAPIError:
        api_exception = cls(
            message=consortium_exception.message,
            detail=consortium_exception.detail,
        )
        own_code = cls.__dict__.get("code")
        api_exception.code = (
            own_code if own_code is not None else consortium_exception.code
        )
        return api_exception
