from enum import StrEnum


class EventType(StrEnum):
    START_SERVER = "START_SERVER"
    STOP_SERVER = "STOP_SERVER"

    LISTENER_CREATED = "LISTENER_CREATED"
    LISTENER_ADDED = "LISTENER_ADDED"
    LISTENER_UPDATED = "LISTENER_UPDATED"
    LISTENER_REMOVED = "LISTENER_REMOVED"
    LISTENER_STARTED = "LISTENER_STARTED"
    LISTENER_STOPPED = "LISTENER_STOPPED"
    LISTENER_CANCELLED = "LISTENER_CANCELLED"

    AGENT_GENERATOR_CREATED = "AGENT_GENERATOR_CREATED"
    AGENT_GENERATOR_ADDED = "AGENT_GENERATOR_ADDED"
    AGENT_GENERATOR_UPDATED = "AGENT_GENERATOR_UPDATED"
    AGENT_GENERATOR_REMOVED = "AGENT_GENERATOR_REMOVED"
    AGENT_GENERATOR_STARTED = "AGENT_GENERATOR_STARTED"
    AGENT_GENERATOR_STOPPED = "AGENT_GENERATOR_STOPPED"
    AGENT_GENERATOR_CANCELLED = "AGENT_GENERATOR_CANCELLED"

    AGENT_REGISTERED = "AGENT_REGISTERED"
    AGENT_CHECKED_IN = "AGENT_CHECKED_IN"
    AGENT_UPDATED = "AGENT_UPDATED"
    AGENT_DEREGISTERED = "AGENT_DEREGISTERED"
    AGENT_TASKED = "AGENT_TASKED"
    AGENT_TASK_COMPLETED = "AGENT_TASK_COMPLETED"

    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"

    PAYLOAD_CREATED = "PAYLOAD_CREATED"
    PAYLOAD_UPDATED = "PAYLOAD_UPDATED"
    PAYLOAD_DELETED = "PAYLOAD_DELETED"

    # TODO: Implement the rest of these events
    LISTENER_RUNTIME_ERRORED = "LISTENER_RUNTIME_ERRORED"
    AGENT_GENERATOR_RUNTIME_ERRORED = "AGENT_GENERATOR_RUNTIME_ERRORED"

    ASSET_CREATED = "ASSET_CREATED"
    ASSET_UPDATED = "ASSET_UPDATED"
    ASSET_DELETED = "ASSET_DELETED"

    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    ARTIFACT_UPDATED = "ARTIFACT_UPDATED"
    ARTIFACT_DELETED = "ARTIFACT_DELETED"
