from enum import StrEnum


class EventType(StrEnum):
    START_SERVER = "START_SERVER"
    STOP_SERVER = "STOP_SERVER"

    LISTENER_CREATED = "LISTENER_CREATED"
    LISTENER_ADDED = "LISTENER_ADDED"
    LISTENER_UPDATED = "LISTENER_UPDATED"
    LISTENER_REMOVED = "LISTENER_REMOVED"
    LISTENER_STARTED = "LISTENER_STARTED"
    LISTENER_STOPPED = "LISTENER_STOPPED"
    LISTENER_CANCELLED = "LISTENER_CANCELLED"

    AGENT_GENERATOR_CREATED = "AGENT_GENERATOR_CREATED"
    AGENT_GENERATOR_ADDED = "AGENT_GENERATOR_ADDED"
    AGENT_GENERATOR_UPDATED = "AGENT_GENERATOR_UPDATED"
    AGENT_GENERATOR_REMOVED = "AGENT_GENERATOR_REMOVED"
    AGENT_GENERATOR_STARTED = "AGENT_GENERATOR_STARTED"
    AGENT_GENERATOR_STOPPED = "AGENT_GENERATOR_STOPPED"
    AGENT_GENERATOR_CANCELLED = "AGENT_GENERATOR_CANCELLED"

    AGENT_UPDATED = "AGENT_UPDATED"
    AGENT_REGISTERED = "AGENT_REGISTERED"
    AGENT_DEREGISTERED = "AGENT_DEREGISTERED"
    AGENT_CHECKED_IN = "AGENT_CHECKED_IN"
    AGENT_TASKED = "AGENT_TASKED"
    AGENT_RESULT_RECEIVED = "AGENT_RESULT_RECEIVED"

    USER_LOGGED_IN = "USER_LOGGED_IN"
    USER_LOGGED_OUT = "USER_LOGGED_OUT"

    # TODO: Implement the rest of these events
    LISTENER_RUNTIME_ERRORED = "LISTENER_RUNTIME_ERRORED"
    AGENT_GENERATOR_RUNTIME_ERRORED = "AGENT_GENERATOR_RUNTIME_ERRORED"
    # TODO: Future websockets chat API? 👀👀👀
    # USER_SENT_MESSAGE = "USER_SENT_MESSAGE"
