from typing import Any, Generic, Type, TypeVar

from pydantic import BaseModel, create_model

T = TypeVar("T")


class ServerException(Exception):
    # This ensures that there is ever only a single instance of the pydantic model
    # within the entire framework. This is important because duplicate pydantic models
    # with the same name will cause the OpenAPI schema to attempt name mangling leading
    # to ugly schema names. Note that _pydantic_models is a list that is shared amongst
    # all instances of this class and its subclasses.
    _pydantic_models = list()

    # We do not combine the non-null and null detail error models into a single model
    # because an error response will only ever return ONE of the two, not possibly
    # either.
    class NonNullDetailErrorModel(BaseModel, Generic[T]):
        code: str
        message: str
        detail: T

    # Using detail: Any | None = None or Any = None as the pydantic field does not work,
    # the swagger UI refuses to properly render the response model hence the model
    # splitting
    class NullDetailErrorModel(BaseModel):
        code: str
        message: str
        detail: type(None)

    def __init__(
        self,
        status_code: int,
        code: str,
        message: str = "",
        detail: Any = None,
        headers: dict[str, Any] | None = None,
    ) -> None:
        self.code = code
        self.message = message
        self.detail = detail

        self.status_code = status_code
        self.headers = headers

    def to_json(self) -> dict[str, Any]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "detail": self.detail,
            },
        }

    def to_pydantic_model(self) -> Type[BaseModel]:
        # Prevent duplication of pydantic models to keep the OpenAPI schema clean
        for existing_pydantic_model in self._pydantic_models:
            # Check if the existing pydantic model is functionally the same as the
            # current one
            if (
                existing_pydantic_model.model_config["json_schema_extra"]["examples"][0]
                == self.to_json()
            ):
                return existing_pydantic_model

        pydantic_model = create_model(
            f"{self.__class__.__name__}Model",
            error=(
                (
                    self.__class__.NonNullDetailErrorModel[type(self.detail)]
                    if self.detail is not None
                    else self.__class__.NullDetailErrorModel
                ),
                ...,
            ),
        )
        pydantic_model.model_config = {
            "json_schema_extra": {
                "examples": [
                    {
                        "error": {
                            "code": self.code,
                            "message": self.message,
                            # If self.detail is None, this will not be included in
                            # the /openapi.json file that is generated by FastAPI
                            # (https://github.com/tiangolo/fastapi/issues/1082). A
                            # workaround is to manually add in the null detail which
                            # is done in server.py
                            "detail": self.detail,
                        },
                    },
                ],
            },
        }
        self._pydantic_models.append(pydantic_model)
        return pydantic_model


# A special error that has no response body to prevent C2 server fingerprinting from
# unauthorized hosts. This error does not inherit from ServerException because it exists
# solely as an exception model to be documented in the OpenAPI schema.
class UnauthorizedError:
    def __init__(self) -> None:
        pass

    @staticmethod
    def to_json() -> None:
        return None

    def to_pydantic_model(self) -> Type[BaseModel]:
        model = create_model(
            f"{self.__class__.__name__}Model",
        )
        model.model_config = {"json_schema_extra": {"example": ""}}
        return model


# HTTP related errors that are not specific to any api endpoint. These errors are raised
# internally by the FastAPI framework and are not raised by the application code. They
# are included here to provide additional data for preprocessing in the custom defined
# server exception handlers at server_exception_handlers.py.
class ForbiddenError(ServerException):
    def __init__(
        self,
        message: str = (
            "Access to the requested resource is forbidden. (Check if the role of your "
            "account has sufficient permissions to access the requested resource.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=403,
            code="FORBIDDEN_ERROR",
            message=message,
            detail=detail,
        )


class NotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested resource could not be found. (Check that the requested "
            "resource URL exists.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class MethodNotAllowedError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested HTTP method is not allowed for this resource. (Use a "
            "different supported HTTP method for the requested resource.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=405,
            code="METHOD_NOT_ALLOWED_ERROR",
            message=message,
            detail=detail,
        )


class UnprocessableEntityError(ServerException):
    def __init__(
        self,
        message: str = (
            "The server cannot process the request due to the client request "
            "containing invalid data. (Check that all provided request data follows "
            "the specified format for the requested resource.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="UNPROCESSABLE_ENTITY_ERROR",
            message=message,
            detail=detail,
        )


class InternalServerError(ServerException):
    def __init__(
        self,
        message: str = "An internal server error occurred. (Try again later.)",
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=500,
            code="INTERNAL_SERVER_ERROR",
            message=message,
            detail=detail,
        )


class ServiceUnavailableError(ServerException):
    def __init__(
        self,
        message: str = (
            "The server is currently in the process of shutting down and is no longer "
            "accepting any more requests.(Try again later.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=503,
            code="SERVICE_UNAVAILABLE_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the api endpoint /api/user-accounts.
class UserAccountNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested user account was not found. (Check that the user_id URL "
            "parameter is correct.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="USER_ACCOUNT_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class DuplicateUserAccountCreationError(ServerException):
    def __init__(
        self,
        message: str = (
            "The new user account contains a username that already exists. (Use a "
            "different username for the new account or delete the old account.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=409,
            code="DUPLICATE_USER_ACCOUNT_CREATION_ERROR",
            message=message,
            detail=detail,
        )


class IdenticalUserAccountPasswordError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided password is identical to the existing password being used "
            "for the target user account. (Use a different password.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=400,
            code="IDENTICAL_USER_ACCOUNT_PASSWORD_ERROR",
            message=message,
            detail=detail,
        )


class EmptyUserAccountPasswordError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided password value is an empty string. (Use a password with at "
            "least one character. To specify that an account have no password at all, "
            "the provided password value should be null.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=400,
            code="IDENTICAL_USER_ACCOUNT_PASSWORD_ERROR",
            message=message,
            detail=detail,
        )


class IdenticalUserAccountRoleError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided role is identical to the existing role being used for the "
            "target user account. (Use a different role.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=400,
            code="IDENTICAL_USER_ACCOUNT_ROLE_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the api endpoint /api/login.
class AlreadyLoggedInError(ServerException):
    def __init__(
        self,
        message: str = (
            "The user is already logged in. (Log out before attempting to log in "
            "again.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=409,
            code="ALREADY_LOGGED_IN_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the api endpoint /api/users.
class UserNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested user was not found. (Check that the user_id URL parameter "
            "is correct.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="USER_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the api endpoint /api/listener-templates.
class ListenerTemplateNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested listener template was not found. (Check that the "
            "listener_template_id URL parameter is correct.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="LISTENER_TEMPLATE_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class InvalidListenerTemplateOptionNameError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided listener template option name is invalid. (Check that the "
            "option name exists.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_LISTENER_TEMPLATE_OPTION_NAME_ERROR",
            message=message,
            detail=detail,
        )


class InvalidListenerTemplateOptionValueError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided listener template option value is invalid. (Check that the "
            "type and format of the option's value is valid.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_LISTENER_TEMPLATE_OPTION_VALUE_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the api endpoint /api/listeners.
class ListenerNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested listener was not found. Please check that the listener_id "
            "URL parameter is correct and try again."
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="LISTENER_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class InvalidListenerOptionNameError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided listener option name is invalid. (Check that the option name "
            "exists.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_LISTENER_OPTION_NAME_ERROR",
            message=message,
            detail=detail,
        )


class InvalidListenerOptionValueError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided listener option value is invalid. (Check that the type and "
            "format of the option's value is valid.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_LISTENER_OPTION_VALUE_ERROR",
            message=message,
            detail=detail,
        )


class ListenerStillRunningError(ServerException):
    def __init__(self, message: str = "", detail: Any = None) -> None:
        super().__init__(
            status_code=409,
            code="LISTENER_STILL_RUNNING_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the endpoint /api/agent-templates.
class AgentTemplateNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested agent template was not found. (Check that the "
            "agent_template_id URL parameter is correct.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="AGENT_TEMPLATE_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class InvalidAgentTemplateOptionNameError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided agent template option name is invalid. (Check that "
            "the option name exists.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_AGENT_TEMPLATE_OPTION_NAME_ERROR",
            message=message,
            detail=detail,
        )


class InvalidAgentTemplateOptionValueError(ServerException):
    def __init__(
        self,
        message: str = (
            "The provided agent template option value is invalid. (Check "
            "that the type and format of the option's value is valid.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=422,
            code="INVALID_AGENT_TEMPLATE_OPTION_VALUE_ERROR",
            message=message,
            detail=detail,
        )


# Errors for the endpoint /api/agent-generators.
class AgentGeneratorNotFoundError(ServerException):
    def __init__(
        self,
        message: str = (
            "The requested agent generator was not found. (Check that the "
            "agent_generator_id URL parameter is correct.)"
        ),
        detail: Any = None,
    ) -> None:
        super().__init__(
            status_code=404,
            code="AGENT_GENERATOR_NOT_FOUND_ERROR",
            message=message,
            detail=detail,
        )


class AgentGeneratorStillRunningError(ServerException):
    def __init__(self, message: str = "", detail: Any = None) -> None:
        super().__init__(
            status_code=409,
            code="AGENT_GENERATOR_STILL_RUNNING_ERROR",
            message=message,
            detail=detail,
        )


# Internal exceptions for the agent templates service. These do not inherit
# from ServerException because they should not be handled by the server exception
# handlers
class InvalidAgentProjectManifestFileError(Exception):
    pass


class InvalidAgentProjectFolderStructureError(Exception):
    pass


class InvalidAgentProjectSymbolError(Exception):
    pass


class InvalidAgentProjectImplementationError(Exception):
    pass


class InternalAgentProjectError(Exception):
    pass


# Internal exceptions for the listener templates service. These do not inherit
# from ServerException because they should not be handled by the server exception
# handlers
class InvalidListenerProjectManifestFileError(Exception):
    pass


class InvalidListenerProjectFolderStructureError(Exception):
    pass


class InvalidListenerProjectSymbolError(Exception):
    pass


class InvalidListenerProjectImplementationError(Exception):
    pass


class InternalListenerProjectError(Exception):
    pass


# Internal exceptions for the user accounts service. These do not inherit from
# ServerException because they should not be handled by the server exception handlers
class InvalidUserAccountError(Exception):
    pass


class DuplicateUsernamesError(Exception):
    pass


class UserAccountsFileNotFoundError(Exception):
    pass


class InvalidUserAccountsFileError(Exception):
    pass
