site_name: Consortium Documentation
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.annotate
    - navigation.sections
nav:
  - Consortium: index.md
  - API:
    - Events Websockets API:
      - events-websockets-api/introduction.md
      - events-websockets-api/authentication.md
      - events-websockets-api/sending-action-commands.md
    - REST API:
      - rest-api/introduction.md
  - Framework:
    - framework/introduction.md
    - framework/listeners-framework.md
    - framework/agents-framework.md
    - framework/plugins-framework.md
    - framework/event-hooks-framework.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - tables
