site_name: Consortium
site_author: not-sekiun
site_description:
  Consortium is a programming language agnostic, and networking
  protocol agnostic command and control (C2) framework that is designed to be
  collaborative, highly extensible, and modular

repo_url: https://github.com/not-sekiun/PyIris
repo_name: not-sekiun/Consortium
edit_uri: docs/

copyright: Copyright &copy; 2016 - 2024 not-sekiun

theme:
  name: material
  font:
    code: JetBrains mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - About:
    - about/features.md
    - about/motivation.md
    - about/history.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/updating.md
    - getting-started/quick-start.md
  - Manual:
    - manual/introduction.md
  - Server API:
    - Events Websockets API:
      - events-websockets-api/introduction.md
      - events-websockets-api/authentication.md
      - events-websockets-api/sending-action-commands.md
    - REST API:
      - rest-api/introduction.md
  - Framework Reference:
    - reference/listeners-reference.md
    - reference/agent-generators-reference.md
    - reference/plugins-reference.md
    - reference/event-hooks-reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - tables

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          filters:
          - '!^_'

extra_javascript:
  - javascripts/asciinema-player.min.js
extra_css:
  - stylesheets/asciinema-player.css
